import type * as React from "react";

import { useCourtText } from "@/components/court/court-provider";
import { cn } from "@/lib/utils";

/**
 * Paper facsimiles of the three generated bundle pages.
 *
 * These are not product chrome — they are what the complaint PDF looks like, so they use
 * the DS's `paper-*` family (`paper`, `paper-foreground`, `paper-muted-foreground`,
 * `paper-border`) and nothing else. The scanned affidavit carries the blurred paragraph
 * the officer is meant to catch.
 */
const PAGE =
  "min-h-[34rem] bg-paper px-12 py-10 text-body-compact leading-relaxed text-paper-foreground";
const HEADING = "text-center text-body-compact font-bold tracking-wide";
const SUB = "mb-3.5 text-center text-caption text-paper-muted-foreground";
const PARA = "mt-3";
const FOOT = "mt-6 text-center text-caption text-paper-muted-foreground";

function Synopsis() {
  const courtText = useCourtText();
  return (
    <div className={PAGE}>
      <h4 className={HEADING}>{courtText("IN THE 24×7 ON COURT AT AHMEDABAD")}</h4>
      <div className={SUB}>
        {courtText("Criminal Complaint (CMP) No.")} ______ of 2026 · Under Section 138, Negotiable
        Instruments Act, 1881
        <br />
        Prateek Agrawal (Complainant) v. Deepak Choudhary (Accused)
      </div>
      <h4 className={cn(HEADING, "mt-1.5")}>SYNOPSIS</h4>
      <div className={PARA}>
        1. The accused issued cheque no. 230270 dated 05/04/2019 drawn on State Bank
        of India for ₹52,05,000 towards discharge of a legally enforceable debt.
      </div>
      <div className={PARA}>
        2. On presentation, the cheque was returned unpaid with the endorsement
        &ldquo;funds insufficient&rdquo; vide return memo dated 04/04/2016.
      </div>
      <div className={PARA}>
        3. A legal demand notice dated 12/04/2016 was dispatched by registered post;
        despite service, no payment was received within the statutory period.
      </div>
      <div className={PARA}>
        4. The complainant therefore prays that cognizance be taken and the accused be
        tried and punished under Section 138 of the Act.
      </div>
      <div className={FOOT}>
        {courtText("Generated by ON Courts")} from the filed fields · Doc 1 of 7
      </div>
    </div>
  );
}

const CELL = "border border-paper-border px-2 py-1.5 align-top";

function Complaint() {
  const courtText = useCourtText();
  return (
    <div className={PAGE}>
      <h4 className={HEADING}>COMPLAINT — FILED DETAILS</h4>
      <div className={SUB}>
        All values below were entered by the advocate at filing and render into the
        complaint PDF verbatim.
      </div>
      <table className="mt-2 w-full border-collapse text-caption">
        <tbody>
          {[
            [
              "Complainant",
              "Prateek Agrawal · B-403, Shyam Avirah, Nava Naroda, Ahmedabad — 382345",
            ],
            [
              "Accused",
              "Deepak Choudhary · 12, Shanti Kunj Society, Naroda, Ahmedabad — 382330",
            ],
            [
              "Cheque",
              "No. 230270 · 05/04/2019 · ₹52,05,000 · State Bank of India (SBIN0007558)",
            ],
            ["Return", "Presented 04/04/2016 · returned “funds insufficient”"],
            [
              "Demand notice",
              "Dated 12/04/2016 · registered post (RPAD) · delivered · no reply, no payment",
            ],
          ].map(([term, detail]) => (
            <tr key={term}>
              <td className={cn(CELL, "w-[38%] text-paper-muted-foreground")}>
                {term}
              </td>
              <td className={CELL}>{detail}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className={PARA}>
        <b className="font-semibold">PRAYER.</b> It is most respectfully prayed that
        this Hon&rsquo;ble Court may be pleased to take cognizance of the offence
        committed by the accused under Section 138 of the Negotiable Instruments Act,
        1881; direct the accused to pay compensation of ₹52,05,000 with interest @ 6%
        p.a. from the date of dishonour; and grant such other and further reliefs as
        this Hon&rsquo;ble Court may deem fit.
      </div>
      {/*
       * eSign blocks: the observed workaround was downloading the PDF into Acrobat
       * just to see who had signed it.
       */}
      <div className="mt-5 flex gap-3.5">
        {[
          ["PRATEEK AGRAWAL", "", "03/07/2026 · 14:22 IST · Aadhaar eSign"],
          [
            "ADV. BIJINI REJEN",
            " (G/60/1992)",
            "03/07/2026 · 14:31 IST · Aadhaar eSign",
          ],
        ].map(([name, suffix, stamp]) => (
          <div
            key={name}
            className="flex-1 border border-dashed border-paper-border p-2 text-caption text-paper-muted-foreground"
          >
            ✓ Digitally signed by
            <br />
            <b className="font-semibold text-paper-foreground">{name}</b>
            {suffix}
            <br />
            {stamp}
          </div>
        ))}
      </div>
      <div className={FOOT}>{courtText("Generated by ON Courts")} · Doc 2 of 7</div>
    </div>
  );
}

function Affidavit() {
  return (
    <div className={PAGE}>
      <h4 className={HEADING}>AFFIDAVIT</h4>
      <div className={SUB}>(Scanned &amp; signed copy uploaded by the complainant)</div>
      <div className={PARA}>
        I, Prateek Agrawal, son of Suresh Agrawal, aged about 41 years, residing at
        B-403, Shyam Avirah, Nava Naroda, Ahmedabad, do hereby solemnly affirm and
        state that I am the complainant in the above case and am fully conversant with
        the facts and circumstances of the case.
      </div>
      {/* The illegible paragraph — the thing the officer is meant to catch. */}
      <div className={cn(PARA, "opacity-70 blur-[1.4px] select-none")}>
        I state that the contents of the accompanying complaint have been read over and
        explained to me, and the same are true and correct to the best of my knowledge,
        belief and information, and nothing material has been concealed therefrom. The
        documents filed along with the complaint are true copies of their respective
        originals.
      </div>
      <div className={PARA}>
        I am competent to swear this affidavit and no part of it is false.
      </div>
      <div className="mt-8 flex items-end justify-between">
        <div>
          Sworn at Ahmedabad
          <br />
          on this 3rd day of July, 2026
        </div>
        <div className="text-center">
          {/* A signature facsimile, not a heading — but it takes the title role's size,
              so it carries the weight the typography gate requires of that role. */}
          <div className="font-[cursive] text-title-s font-semibold">
            P. Agrawal
          </div>
          DEPONENT
        </div>
      </div>
    </div>
  );
}

export const GENERATED_PAGES: Record<string, () => React.ReactElement> = {
  synopsis: Synopsis,
  complaint: Complaint,
  affidavit: Affidavit,
};
