import assert from "node:assert/strict";
import test from "node:test";

import { caseSearchKey, localizeCaseNumber, localizeCourtText, localizeDeep } from "./localize";

test("Kerala is the designed baseline and passes through untouched", () => {
  const text = "Before the JMFC Court 1 · ST/6/2025 · CMP/58/2025 · KL-000049-2025 · 24×7 ON Court";
  assert.equal(localizeCourtText(text, "kerala"), text);
  assert.equal(localizeCaseNumber("KLKM520000232025", "kerala"), "KLKM520000232025");
});

test("Gujarat numbers each stage the CIS way", () => {
  assert.equal(localizeCaseNumber("ST/6/2025", "gujarat"), "eCC/6/2025");
  assert.equal(localizeCaseNumber("ST 412/2025", "gujarat"), "eCC/412/2025");
  // Registration takes the classification; the sequence picks it, stably.
  assert.equal(localizeCaseNumber("CMP/55/2025", "gujarat"), "eCC/55/2025");
  assert.equal(localizeCaseNumber("CMP/58/2025", "gujarat"), "eCR EN/58/2025");
  assert.equal(localizeCaseNumber("CMP/59/2025", "gujarat"), "eCR MA/59/2025");
  assert.equal(localizeCaseNumber("KL-000049-2025", "gujarat"), "GJ-000049-2025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "gujarat"), "GJAH010000232025");
});

test("Punjab and Haryana number with NACT and their own CNR prefixes", () => {
  assert.equal(localizeCaseNumber("KL-000049-2025", "haryana"), "NACT/49/2025");
  assert.equal(localizeCaseNumber("CMP/58/2025", "haryana"), "NACT/58/2025");
  assert.equal(localizeCaseNumber("ST 6/2025", "punjab"), "NACT/6/2025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "haryana"), "HRPK030000232025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "punjab"), "PBXX030000232025");
});

test("court names take the state's placeholder, in either case", () => {
  assert.equal(localizeCourtText("before 24×7 ON Court.", "gujarat"), "before Gujarat Court.");
  assert.equal(localizeCourtText("Generated by ON Courts", "punjab"), "Generated by Punjab Courts");
  assert.equal(localizeCourtText("IN THE 24×7 ON COURT AT AHMEDABAD", "haryana"), "IN THE HARYANA COURT");
  assert.equal(localizeCourtText("24×7 ON Court, Ahmedabad", "haryana"), "Haryana Court");
  assert.equal(localizeCourtText("Before the JMFC Court 1", "gujarat"), "Before the JMFC Court 1, Gujarat");
});

test("re-voicing is idempotent, so a value shown twice never doubles up", () => {
  const once = localizeCourtText("JMFC Court 1 · CMP/58/2025 · KL-000049-2025", "gujarat");
  assert.equal(localizeCourtText(once, "gujarat"), once);
  const nact = localizeCourtText("JMFC Court 12 · ST/6/2025", "haryana");
  assert.equal(nact, "JMFC Court 12, Haryana · NACT/6/2025");
  assert.equal(localizeCourtText(nact, "haryana"), nact);
});

test("a document is re-voiced whole, and only its strings", () => {
  const when = new Date(2026, 0, 2);
  const doc = {
    court: "Before the JMFC Court 1",
    caseNumber: "ST/6/2025",
    paragraphs: ["In CMP/58/2025 before 24×7 ON Court."],
    when,
    pages: 3,
  };
  const out = localizeDeep(doc, "punjab");
  assert.equal(out.court, "Before the JMFC Court 1, Punjab");
  assert.equal(out.caseNumber, "NACT/6/2025");
  assert.deepEqual(out.paragraphs, ["In NACT/58/2025 before Punjab Court."]);
  assert.equal(out.when, when);
  assert.equal(out.pages, 3);
  assert.equal(localizeDeep(doc, "kerala"), doc);
});

test("only Punjab's filing step drops the oath", () => {
  assert.equal(localizeCourtText("Sign and oath", "punjab"), "Sign");
  assert.equal(localizeCourtText("Sign and oath", "haryana"), "Sign and oath");
  assert.equal(localizeCourtText("Sign and oath", "gujarat"), "Sign and oath");
});

test("a number typed the way a state shows it finds the Kerala record underneath", () => {
  assert.equal(caseSearchKey("  NACT/241/2026 "), "241/2026");
  assert.equal(caseSearchKey("eCR EN/58/2025"), "58/2025");
  assert.equal(caseSearchKey("eCC/6"), "6");
  assert.equal(caseSearchKey("GJ-000049-2025"), "kl-000049-2025");
  assert.equal(caseSearchKey("HRPK030000232025"), "klkm520000232025");
  // Kerala queries and names are only lower-cased.
  assert.equal(caseSearchKey("ST/6/2025"), "st/6/2025");
  assert.equal(caseSearchKey("Anand Traders"), "anand traders");
  assert.ok("st 241/2026".includes(caseSearchKey("NACT/241/2026")));
});
