import assert from "node:assert/strict";
import test from "node:test";

import { caseSearchKey, localizeCaseNumber, localizeCourtText, localizeDeep } from "./localize";

test("Kerala is the designed baseline and passes through untouched", () => {
  const text = "Before the JMFC Court 1 · ST/6/2025 · CMP/58/2025 · KL-000049-2025 · 24×7 ON Court";
  assert.equal(localizeCourtText(text, "kerala"), text);
  assert.equal(localizeCaseNumber("KLKM520000232025", "kerala"), "KLKM520000232025");
});

test("Gujarat numbers each stage the CIS way", () => {
  assert.equal(localizeCaseNumber("ST/6/2025", "gujarat"), "eCC/6/2025");
  assert.equal(localizeCaseNumber("ST 412/2025", "gujarat"), "eCC/412/2025");
  // Registration takes the classification; the sequence picks it, stably.
  assert.equal(localizeCaseNumber("CMP/55/2025", "gujarat"), "eCC/55/2025");
  assert.equal(localizeCaseNumber("CMP/58/2025", "gujarat"), "eCR EN/58/2025");
  assert.equal(localizeCaseNumber("CMP/59/2025", "gujarat"), "eCR MA/59/2025");
  assert.equal(localizeCaseNumber("KL-000049-2025", "gujarat"), "GJ-000049-2025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "gujarat"), "GJAH010000232025");
});

test("Punjab and Haryana number with NACT and their own CNR prefixes", () => {
  assert.equal(localizeCaseNumber("KL-000049-2025", "haryana"), "NACT/49/2025");
  assert.equal(localizeCaseNumber("CMP/58/2025", "haryana"), "NACT/58/2025");
  assert.equal(localizeCaseNumber("ST 6/2025", "punjab"), "NACT/6/2025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "haryana"), "HRPK030000232025");
  assert.equal(localizeCaseNumber("KLKM520000232025", "punjab"), "PBXX030000232025");
});

test("court names take the state's placeholder, in either case", () => {
  assert.equal(localizeCourtText("before 24×7 ON Court.", "gujarat"), "before Gujarat Court.");
  assert.equal(localizeCourtText("Generated by ON Courts", "punjab"), "Generated by Punjab Courts");
  assert.equal(localizeCourtText("IN THE 24×7 ON COURT AT AHMEDABAD", "haryana"), "IN THE HARYANA COURT");
  assert.equal(localizeCourtText("24×7 ON Court, Ahmedabad", "haryana"), "Haryana Court");
  assert.equal(localizeCourtText("Before the JMFC Court 1", "gujarat"), "Before the JMFC Court 1, Gujarat");
});

test("re-voicing is idempotent, so a value shown twice never doubles up", () => {
  const once = localizeCourtText("JMFC Court 1 · CMP/58/2025 · KL-000049-2025", "gujarat");
  assert.equal(localizeCourtText(once, "gujarat"), once);
  const nact = localizeCourtText("JMFC Court 12 · ST/6/2025", "haryana");
  assert.equal(nact, "JMFC Court 12, Haryana · NACT/6/2025");
  assert.equal(localizeCourtText(nact, "haryana"), nact);
});

test("a document is re-voiced whole, and only its strings", () => {
  const when = new Date(2026, 0, 2);
  const doc = {
    court: "Before the JMFC Court 1",
    caseNumber: "ST/6/2025",
    paragraphs: ["In CMP/58/2025 before 24×7 ON Court."],
    when,
    pages: 3,
  };
  const out = localizeDeep(doc, "punjab");
  assert.equal(out.court, "Before the JMFC Court 1, Punjab");
  assert.equal(out.caseNumber, "NACT/6/2025");
  assert.deepEqual(out.paragraphs, ["In NACT/58/2025 before Punjab Court."]);
  assert.equal(out.when, when);
  assert.equal(out.pages, 3);
  assert.equal(localizeDeep(doc, "kerala"), doc);
});

test("only Punjab's filing step drops the oath", () => {
  assert.equal(localizeCourtText("Sign and oath", "punjab"), "Sign");
  assert.equal(localizeCourtText("Sign and oath", "haryana"), "Sign and oath");
  assert.equal(localizeCourtText("Sign and oath", "gujarat"), "Sign and oath");
});

test("a number typed the way a state shows it finds the Kerala record underneath", () => {
  assert.equal(caseSearchKey("  NACT/241/2026 "), "241/2026");
  assert.equal(caseSearchKey("eCR EN/58/2025"), "58/2025");
  assert.equal(caseSearchKey("eCC/6"), "6");
  assert.equal(caseSearchKey("GJ-000049-2025"), "kl-000049-2025");
  assert.equal(caseSearchKey("HRPK030000232025"), "0000232025");
  // Kerala queries and names are only lower-cased.
  assert.equal(caseSearchKey("ST/6/2025"), "st/6/2025");
  assert.equal(caseSearchKey("Anand Traders"), "anand traders");
  assert.ok("st 241/2026".includes(caseSearchKey("NACT/241/2026")));
});

test("scrutiny's Ahmedabad filing numbers stay in Gujarat and become NACT elsewhere", () => {
  assert.equal(localizeCaseNumber("F/AHM/2026/00319", "gujarat"), "F/AHM/2026/00319");
  assert.equal(localizeCaseNumber("F/AHM/2026/00319", "haryana"), "NACT/319/2026");
  assert.equal(localizeCaseNumber("F/AHM/2026/00319", "kerala"), "F/AHM/2026/00319");
});

test("Kerala's sample places, PIN codes and Bar numbers move to the state", () => {
  assert.equal(
    localizeCourtText("Sreenilayam, Chinnakada, Kollam, Kerala — 691001", "gujarat"),
    "Shanti Kunj, Navrangpura, Ahmedabad, Gujarat — 381001",
  );
  assert.equal(localizeCourtText("Kollam East police station", "haryana"), "Panchkula East police station");
  assert.equal(localizeCourtText("Kerala Gramin Bank, Punalur", "punjab"), "Punjab Gramin Bank, Khanna");
  assert.equal(localizeCourtText("Court language: Malayalam", "gujarat"), "Court language: Gujarati");
  assert.equal(localizeCourtText("KL/1109/2009 · K/1234/2020", "haryana"), "HR/1109/2009 · P/1234/2020");
  // Amounts and longer numbers are not PIN codes.
  assert.equal(localizeCourtText("₹6,91,001 · 6910012345", "gujarat"), "₹6,91,001 · 6910012345");
  assert.equal(localizeCourtText("Cheque number 691234", "gujarat"), "Cheque number 691234");
  assert.equal(localizeCourtText("PIN 690518", "punjab"), "PIN 140518");
  const once = localizeCourtText("Chinnakada, Kollam 691001", "punjab");
  assert.equal(localizeCourtText(once, "punjab"), once);
  assert.equal(localizeCourtText("Chinnakada, Kollam", "kerala"), "Chinnakada, Kollam");
});

test("the scrutiny queue's Ahmedabad filings stay in Gujarat and move elsewhere", () => {
  const address = "335, Sardar Complex, Nikol, Ahmedabad, Gujarat — 380008";
  assert.equal(localizeCourtText(address, "gujarat"), address);
  assert.equal(localizeCourtText(address, "haryana"), "335, Sardar Complex, Nikol, Panchkula, Haryana — 130008");
});

test("names in Malayalam script, Bar applications and lone PIN fields follow the state", () => {
  assert.equal(localizeCourtText("അനിൽകുമാർ പി. നായർ", "gujarat"), "અનિલકુમાર પી. નાયર");
  assert.equal(localizeCourtText("KL-ADV-000164-2026", "haryana"), "HR-ADV-000164-2026");
  assert.deepEqual(localizeDeep({ pin: "680664", cheque: "680664" }, "punjab"), { pin: "140664", cheque: "680664" });
});

test("CNRs from any Kerala establishment take the state's prefix", () => {
  assert.equal(localizeCaseNumber("KLKM010016292025", "punjab"), "PBXX030016292025");
});

test("house names and the scrutiny queue's Gujarat Bar numbers follow the state", () => {
  assert.equal(localizeCourtText("Puthenveedu, Market Road, Kodungallur", "punjab"), "Guru Kripa, Market Road, Kapurthala");
  assert.equal(localizeCourtText("G/111/2011", "haryana"), "P/111/2011");
  assert.equal(localizeCourtText("G/111/2011", "gujarat"), "G/111/2011");
});

test("every Kerala locality in the data has a stand-in, the same one each time", () => {
  const once = localizeCourtText("Thevally, Asramam and Mundakkal", "gujarat");
  assert.doesNotMatch(once, /Thevally|Asramam|Mundakkal/);
  assert.equal(localizeCourtText("Thevally", "gujarat"), localizeCourtText("Thevally", "gujarat"));
  assert.equal(localizeCourtText("Bar Council of Kerala", "haryana"), "Bar Council of Punjab and Haryana");
  assert.equal(localizeCourtText("Bar Council of Kerala", "gujarat"), "Bar Council of Gujarat");
});
