import { existsSync, lstatSync, readFileSync, readdirSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";

const id = /^[a-z][a-z0-9-]*$/;
const read = (root, path) => readFileSync(join(root, path), "utf8");
const fail = (message) => { throw new Error(message); };
const banner = (source) => `<!-- Generated by npm run sync:rails from ${source}. Edit the source. -->\n\n`;

export function filesUnder(root, directory) {
  const base = join(root, directory);
  if (!existsSync(base)) return [];
  if (lstatSync(base).isSymbolicLink()) fail(`Symlink not supported in managed rails: ${directory}`);
  return readdirSync(base, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))
    .flatMap((entry) => {
      const path = `${directory}/${entry.name}`;
      if (entry.isSymbolicLink()) fail(`Symlink not supported in managed rails: ${path}`);
      return entry.isDirectory() ? filesUnder(root, path) : [path];
    });
}

function assertSource(root, path, prefix) {
  if (typeof path !== "string" || !path.startsWith(prefix) || path.includes("..") ||
      !existsSync(join(root, path)) || !lstatSync(join(root, path)).isFile()) {
    fail(`Missing or invalid canonical source: ${path}`);
  }
  if (lstatSync(join(root, path)).isSymbolicLink()) fail(`Symlink source: ${path}`);
}

// Canonical SKILL.md metadata uses YAML-compatible JSON string scalars. Restricting
// this authored subset keeps validation dependency-free and prevents parser ambiguity.
export function skillMetadata(text, path) {
  const match = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!match) fail(`Missing skill frontmatter: ${path}`);
  const values = {};
  for (const line of match[1].split("\n")) {
    const field = /^(name|description): (.+)$/.exec(line);
    if (!field || values[field[1]] !== undefined) fail(`Unsupported or duplicate skill metadata: ${path}`);
    values[field[1]] = field[2].startsWith('"') ? JSON.parse(field[2]) : field[2];
  }
  if (typeof values.name !== "string" || !id.test(values.name) || values.name.length > 64 ||
      values.name.endsWith("-") || values.name.includes("--") ||
      typeof values.description !== "string" || !values.description.trim() ||
      values.description.length > 1024 || /[<>]/.test(values.description)) {
    fail(`Invalid skill name/description: ${path}`);
  }
  return values;
}

function checkLocalReferences(root, path, text) {
  const candidates = [];
  // Backticked repo paths are the portable convention across native tool directories.
  for (const match of text.matchAll(/`((?:\.agents|\.codex|\.claude|\.cursor|docs|scripts|apps)\/[^`\n]+)`/g)) {
    const target = match[1];
    if (/[<>*|]/.test(target)) continue; // explicitly parameterized examples
    candidates.push([target, resolve(root, target)]);
  }
  // Normal Markdown links in references are relative to that reference file.
  for (const match of text.matchAll(/\[[^\]\n]*\]\(([^)\s]+)\)/g)) {
    const target = match[1].split("#")[0];
    if (!target || /^[a-z]+:|^\//i.test(target) || /[<>*]/.test(target)) continue;
    candidates.push([target, resolve(root, dirname(path), target)]);
  }
  for (const [target, absolute] of candidates) {
    const rel = relative(root, absolute);
    if (rel.startsWith("..") || isAbsolute(rel) || !existsSync(absolute)) {
      fail(`Broken local reference in ${path}: ${target}`);
    }
  }
}

function checkCommands(root, path, text, scripts) {
  for (const match of text.matchAll(/npm run ([a-z][a-z0-9:-]*)/g)) {
    if (!Object.hasOwn(scripts, match[1])) fail(`Unknown root command in ${path}: npm run ${match[1]}`);
  }
  if (/`npm test`/.test(text)) fail(`Unscoped npm test in ${path}; use npm run test:app`);
}

export function expectedRails(root) {
  const manifest = JSON.parse(read(root, ".agents/rails.json"));
  const scripts = JSON.parse(read(root, "package.json")).scripts;
  const profiles = JSON.parse(read(root, ".agents/verification.json"));
  if (manifest.version !== 1 || !Array.isArray(manifest.roles) || !Array.isArray(manifest.rules) ||
      !Array.isArray(manifest.requiredSkills)) fail("Invalid .agents/rails.json schema");
  for (const required of ["agents", "ui"]) {
    if (!Array.isArray(profiles[required]) || !profiles[required].length) fail(`Missing verification profile: ${required}`);
  }
  for (const [profile, commands] of Object.entries(profiles)) {
    if (!id.test(profile) || !Array.isArray(commands) || !commands.length) fail(`Invalid profile: ${profile}`);
    for (const command of commands) {
      if (typeof command !== "string" || !Object.hasOwn(scripts, command) || command.startsWith("verify:") ||
          /^(dev|start|postinstall|setup:ds|ds:bump|sync:)/.test(command)) {
        fail(`Invalid verification command: ${profile}/${command}`);
      }
    }
  }
  for (const [profile, required] of Object.entries({
    agents: ["check:rails", "test:rails"], ui: ["check:ds-fresh", "lint", "check:rails"],
  })) {
    if (required.some((command) => !profiles[profile].includes(command))) {
      fail(`Required verification coverage missing from ${profile}`);
    }
  }
  const output = new Map();
  assertSource(root, manifest.project, ".agents/policies/");
  const project = read(root, manifest.project);
  output.set("AGENTS.md", banner(manifest.project) + project);
  output.set("CLAUDE.md", banner(manifest.project) + project);
  output.set(".cursor/rules/project.mdc", `---\ndescription: "Dristi task routing, sources, ownership, and completion policy"\nalwaysApply: true\n---\n\n${banner(manifest.project)}${project}`);

  const names = new Set();
  for (const role of manifest.roles) {
    const fields = ["name", "description", "source", "claudeTools", "claudeModel", "codexSandbox"];
    if (Object.keys(role).some((field) => !fields.includes(field))) fail(`Unknown role adapter field: ${role.name}`);
    if (typeof role.name !== "string" || !id.test(role.name) || names.has(role.name) || typeof role.description !== "string" ||
        !role.description.trim() || !Array.isArray(role.claudeTools) || !role.claudeTools.length ||
        !role.claudeTools.every((tool) => /^[A-Za-z]+$/.test(tool)) ||
        (role.codexSandbox !== undefined && role.codexSandbox !== "read-only") ||
        typeof role.claudeModel !== "string" || !/^[a-z0-9.-]+$/.test(role.claudeModel)) fail(`Invalid role adapter: ${role.name}`);
    names.add(role.name);
    assertSource(root, role.source, ".agents/roles/");
    if (["ux-designer", "ui-reviewer"].includes(role.name) &&
        (role.codexSandbox !== "read-only" || role.claudeTools.some((tool) => !["Read", "Grep", "Glob", "Skill"].includes(tool)))) {
      fail(`Read-only role adapter weakened: ${role.name}`);
    }
    const body = read(root, role.source);
    // JSON basic strings are valid TOML strings for this text subset. In particular,
    // escaped newlines/quotes avoid multiline delimiter injection from authored prose.
    let toml = `# Generated by npm run sync:rails from ${role.source} and .agents/rails.json\n`;
    toml += `name = ${JSON.stringify(role.name)}\ndescription = ${JSON.stringify(role.description)}\n`;
    if (role.codexSandbox) toml += `sandbox_mode = ${JSON.stringify(role.codexSandbox)}\n`;
    toml += `developer_instructions = ${JSON.stringify(body)}\n`;
    output.set(`.codex/agents/${role.name}.toml`, toml);
    output.set(`.claude/agents/${role.name}.md`, `---\nname: ${role.name}\ndescription: ${JSON.stringify(role.description)}\ntools: ${role.claudeTools.join(", ")}\nmodel: ${role.claudeModel}\n---\n\n${banner(role.source)}${body}`);
    output.set(`.cursor/rules/role-${role.name}.mdc`, `---\ndescription: ${JSON.stringify(role.description)}\nalwaysApply: false\n---\n\n${banner(role.source)}> Cursor role boundaries are instructions, not enforced tool or filesystem restrictions.\n\n${body}`);
  }
  for (const required of ["ux-designer", "ui-designer", "ui-reviewer"]) {
    if (!names.has(required)) fail(`Missing product-team role: ${required}`);
  }
  const ruleNames = new Set(["project"]);
  for (const rule of manifest.rules) {
    if (typeof rule.name !== "string" || !id.test(rule.name) || ruleNames.has(rule.name) || rule.name.startsWith("role-") ||
        typeof rule.description !== "string" || !rule.description.trim()) fail(`Invalid rule: ${rule.name}`);
    ruleNames.add(rule.name);
    assertSource(root, rule.source, ".agents/policies/");
    const body = banner(rule.source) + read(root, rule.source);
    output.set(`.claude/rules/${rule.name}.md`, body);
    output.set(`.cursor/rules/${rule.name}.mdc`, `---\ndescription: ${JSON.stringify(rule.description)}\nalwaysApply: true\n---\n\n${body}`);
  }

  const skillFiles = filesUnder(root, ".agents/skills");
  const skills = new Set();
  for (const path of skillFiles.filter((path) => /^\.agents\/skills\/[^/]+\/SKILL\.md$/.test(path))) {
    const metadata = skillMetadata(read(root, path), path);
    if (path.split("/")[2] !== metadata.name || skills.has(metadata.name)) fail(`Skill folder/name mismatch: ${path}`);
    skills.add(metadata.name);
  }
  for (const skill of manifest.requiredSkills) {
    if (!id.test(skill) || !skills.has(skill)) fail(`Missing required skill: ${skill}`);
  }
  for (const path of skillFiles) {
    if (!skills.has(path.split("/")[2])) fail(`Skill resource without SKILL.md: ${path}`);
    const content = readFileSync(join(root, path));
    output.set(path.replace(".agents/", ".claude/"), content);
    output.set(path.replace(".agents/", ".cursor/"), content);
  }
  const index = "# Generated skills\n\nEdit canonical skills in `.agents/skills/`, then run `npm run sync:rails`.\n" +
    "Tool mirrors include all skill resources. Run `npm run verify:agents` after changes.\n\n" +
    [...skills].sort().map((skill) => `- [${skill}](${skill}/SKILL.md)`).join("\n") + "\n";
  output.set(".claude/skills/README.md", index);
  output.set(".cursor/skills/README.md", index);

  const sourceFiles = [...filesUnder(root, ".agents/policies"), ...filesUnder(root, ".agents/roles"), ...skillFiles];
  const declaredRoles = new Set(manifest.roles.map((role) => role.source));
  for (const path of filesUnder(root, ".agents/roles")) {
    if (!declaredRoles.has(path)) fail(`Role source without adapter: ${path}`);
  }
  for (const path of sourceFiles.filter((path) => path.endsWith(".md"))) {
    const content = read(root, path);
    checkLocalReferences(root, path, content);
    checkCommands(root, path, content, scripts);
  }
  return { output, roles: names.size, skills: skills.size, rules: ruleNames.size };
}

export const managedDirectories = [".codex/agents", ".claude/agents", ".claude/rules", ".claude/skills", ".cursor/rules", ".cursor/skills"];

export function inspectRails(root) {
  const result = expectedRails(root);
  const problems = [];
  for (const [path, content] of result.output) {
    const absolute = join(root, path);
    if (!existsSync(absolute)) problems.push(`Missing generated file: ${path}`);
    else if (lstatSync(absolute).isSymbolicLink() || !lstatSync(absolute).isFile()) problems.push(`Invalid generated file: ${path}`);
    else if (!readFileSync(absolute).equals(Buffer.from(content))) problems.push(`Generated file differs: ${path}`);
  }
  for (const directory of managedDirectories) {
    for (const path of filesUnder(root, directory)) {
      if (!result.output.has(path)) problems.push(`Unexpected managed file (register or remove explicitly): ${path}`);
    }
  }
  // macOS may alias these names; only a distinct legacy directory is an error.
  for (const legacy of [".Codex", ".codex/skills", ".codex/rules"]) {
    if (!existsSync(join(root, legacy))) continue;
    if (legacy === ".Codex" && lstatSync(join(root, legacy)).ino === lstatSync(join(root, ".codex")).ino) continue;
    problems.push(`Unexpected legacy Codex path: ${legacy}`);
  }
  return { ...result, problems };
}
